// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motofushin.Roadmap.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Motofushin.Roadmap    .Infrastructure.Migrations
{
    [DbContext(typeof(ScraperDwhDbContext))]
    [Migration("20260918034902_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scraper_dwh")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motofushin.Roadmap.Infrastructure.Persistence.Entities.DimRoute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LengthM")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PointCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_dim_route_source_external_id");

                    b.ToTable("dim_route", "scraper_dwh");
                });

            modelBuilder.Entity("Motofushin.Roadmap.Infrastructure.Persistence.Entities.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ElevationM")
                        .HasColumnType("numeric(7,1)");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Lon")
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset?>("RecordedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id", "Seq");

                    b.ToTable("route_point", "scraper_dwh");
                });

            modelBuilder.Entity("Motofushin.Roadmap.Infrastructure.Persistence.Entities.RoutePoint", b =>
                {
                    b.HasOne("Motofushin.Roadmap.Infrastructure.Persistence.Entities.DimRoute", "Route")
                        .WithMany("Points")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Motofushin.Roadmap.Infrastructure.Persistence.Entities.DimRoute", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
